name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  ci-build:
    uses: ./.github/workflows/ci-build.yml
    with:
      upload-artifacts: true

  publish-testpypi:
    needs: ci-build
    runs-on: ubuntu-latest

    if: contains(github.ref_name, 'rc') || contains(github.ref_name, 'a') || contains(github.ref_name, 'b')

    environment:
      name: testpypi
      url: https://test.pypi.org/p/pratt-calc

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - uses: astral-sh/setup-uv@v6

      - run: uv publish --index testpypi

  publish-pypi:
    needs: ci-build
    runs-on: ubuntu-latest

    if: |
      !contains(github.ref_name, 'rc') &&
      !contains(github.ref_name, 'a') &&
      !contains(github.ref_name, 'b')

    environment:
      name: pypi
      url: https://pypi.org/p/pratt-calc

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - uses: astral-sh/setup-uv@v6

      - run: uv publish
